### ISSUE TITLE
AWS Bedrock Anthropic Sonnet 4 not working with latest aider 0.84.0

### ISSUE THREAD

**Issue by PierrunoYT** [PierrunoYT/patch#992]
Looks like other people experienced this too -> 

### Issue

Same with me, I've also experienced this one:

Aider v0.84.0
Model: bedrock/anthropic.claude-sonnet-4 with whole edit format
Git repo: .git with 2,917 files
Warning: For large repos, consider using --subtree-only and .aiderignore
See: https://aider.chat/docs/faq.html#can-i-use-aider-in-a-large-mono-repo
Repo-map: using 1024 tokens, auto refresh
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

just say hi back to me

litellm.APIConnectionError: 'AmazonAnthropicConfig' object has no attribute 'aws_authentication_params'
Traceback (most recent call last):
File "C:\Users\Strahinski\aider-env\Lib\site-packages\litellm\main.py", line 2768, in completion
response = base_llm_http_handler.completion(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Strahinski\aider-env\Lib\site-packages\litellm\llms\custom_httpx\llm_http_handler.py", line 270, in completion
data = provider_config.transform_request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Strahinski\aider-env\Lib\site-packages\litellm\llms\bedrock\chat\invoke_transformations\base_invoke_transformation.py", line 201, in transform_request
inference_params = {
^
File "C:\Users\Strahinski\aider-env\Lib\site-packages\litellm\llms\bedrock\chat\invoke_transformations\base_invoke_transformation.py", line 204, in
if k not in self.aws_authentication_params
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AmazonAnthropicConfig' object has no attribute 'aws_authentication_params'

**Comment by PierrunoYT** [comment]
Closing as not planned: the traceback is an `AmazonAnthropicConfig` AttributeError inside LiteLLM Bedrock support, an external dependency failure from Aider 0.84.0.
